### PR TITLE
SwiftCOM: implement `IUnknown.perform(as:_:)`

### PR DESCRIPTION
**Pull request by compnerd**
Add a new helper to execute a closure as a specific type.  The idea
to use the type as an argument is originally from STREGA's Gate which
made this abstraction possible.

### CODE REVIEW

**Comment by compnerd** [comment]
@STREGAsGate, I think that this is a good first step towards the simplification that you had pointed out.  The examples you had suggested seemed to pass in `HRESULT` rather than creating a local variable, which I don't understand the value of.  Could you explain what you had in mind?

**Comment by STREGAsGate** [comment]
[Here's the implementation I've built so far.](https://gist.github.com/STREGAsGate/07f90974b920041bc8d806b5f0362607) I don't necessarily in love the function names.

The intention is to make all the boilerplate one-linable. Autocomplete is just as fast as copy/paste or snippets that way.
The hresult being an inout isn't sexy, but it is just for internal use for these implementations and using inout's allows the same API to be expanded to include other scenarios later while keeping the same syntax.

This also makes everything go through to same pipe so changes are simple later. For instance using a closure style API would allow atomic/synchronization additions later if that ever became necessary.

**Comment by STREGAsGate** [comment]
`perform(as:)` is a much better name :)

**Comment by compnerd** [comment]
Yeah, I get the desire to make the boilerplate something that can be extracted.  I definitely would love to do that.  My problem with the `inout HRESULT` is that there is no guarantee that the result is a `HRESULT` or that it needs to be checked.  `ID3D12CommandList::GetType` is a good example: https://github.com/compnerd/swift-com/pull/21/files#diff-5a0dd0db466c10a0cf90a3609091a8cde0b050dd898424ad775ad147af679909.  The `HRESULT` is entirely unnecessary:

```
  return perform(as: WinSDK.ID3D12CommandList.self) { pThis in
    return pThis.pointee.lpVtbl.pointee.GetType(pThis)
  }
```

**Comment by STREGAsGate** [comment]
Yup, that's why I did a different function for the hresult version. It has almost an identical signature though so code completion would suggest it and help discovery. The hresult != S_OK seemed common enough that having it was benefitial.
    
    return perform(as: WinSDK.ID3D12CommandList.self) { (pThis, throwfNotS_OK) in
        throwfNotS_OK = theValueIfThisActuallyUsedHRESULT
        return pThis.pointee.lpVtbl.pointee.GetType(pThis)
    }

So there wouldn't be any downside, if you don't need the hresult just don't include it in the closure and the compiler will use the simpler version.

To your additionally comment, I intended to include a `throwIfNot: Set<HRESULT> = [S_OK]` in the function to make it more flexible, but I didn't run into anything other then S_OK yet.

And if we needed to add a new function for something that's implemented a lot, we'd use the same signature again with whatever extra stuff we need.

I was going for more of a collection of functions with a similar pattern rather then a catch all type of thing.

**Comment by compnerd** [comment]
Hmm, I think I would prefer that something like this instead:

```swift
func checked(_ body: @autoclosure () -> HRESULT) throws {
  let hr: HRESULT = body()
  guard hr == S_OK else { throw COMError(hr: hr) }
}
```

Its not exactly as convenient, but still isn't too terrible:

```swift
  public func EnumObjectParams() throws -> IEnumString {
    return try perform(as: WinSDK.IBindCtx.self) { pThis in
      var pEnum: UnsafeMutablePointer<WinSDK.IEnumString>?
      checked(pThis.pointee.lpVtbl.pointee.EnumObjectParam(pThis, &pEnum))
      return IEnumString(pUnk: pEnum)
    }
  }
```

**Comment by STREGAsGate** [comment]
Yeah, that looks nice. Not one line but it's much easier to understand.
Maybe add this in to cover the multi succeed situation? The Set is just scalars so it shouldn't be a performance issue I don't think.
     
    func checkResult(_ body: @autoclosure () -> HRESULT, is passable: Set<HRESULT> = [S_OK]) throws {
        let hr: HRESULT = body()
        guard passable.contains(hr) else { throw COMError(hr: hr) }
    }

**Comment by STREGAsGate** [comment]
And the last thing I noticed we need is this. To gain access to pointer that are passed into functions.

    final internal func pointerToThis<T>(_ type: T.Type) throws -> UnsafeMutablePointer<T> {
        return try self.perform(as: type) { (pThis) in
            return pThis
        }
    }

It would cool if we could add a generator object to the closure based function that will vend these pointers on demand so people don't just use this directly in their top level implementation. This also shouldn't use the closure to get the pointer so it's not looping through the closure over and over.

Maybe move everything into the vender type?

    return perform(as: WinSDK.ID3D12CommandList.self) { (com) in
        let pMyPointer = com.pointer(from: myInObject.pUnk, as: WinSDK.MyThing.self)
        com.checkResult(com.pThis.pointee.lpVtbl.pointee.GetType(pThis), is: [S_OK, S_FALSE]) 
    }

This would be more infinatley scalable, but might be getting a little carried away...

**Comment by STREGAsGate** [comment]
I'm gonna implement the vender version real quick. I'm curious how it'll look / perform.

**Comment by STREGAsGate** [comment]
Okay here's what I was thinking.
https://gist.github.com/STREGAsGate/0458531542ca3a887fc6e37fcd506778

**Comment by compnerd** [comment]
So, thinking a bit more about this, I think that I might want to do something like this:

```swift
@discardableResult
func CHECKED(_ body: @autoclosure () -> HRESULT) throws -> HRESULT {
  let hr: HRESULT = body()
  guard hr >= 0 else { throw COMError(hr: hr) }
  return hr
}
```

This allows handling of the `HRESULT` for different values if needed, but will implicitly throw an error if a failure is raised.  This is based on the `SUCCEEDED` macro winerror.h (https://docs.microsoft.com/en-us/windows/win32/api/winerror/nf-winerror-succeeded).  This way we don't need to explicitly handle the cases and can map the result in place if necessary.  Most of the cases do not require that and the result can be silently discarded there.

For the `pointerToThis`, I have to ask, what doesn't work with [`RawPointer`](https://github.com/compnerd/swift-com/blob/master/Sources/SwiftCOM/Support/RawTyped.swift#L10-L17)?

```swift
  public func ApplyPropertiesToItem(_ psiItem: IShellItem) throws {
    return try perform(as: WinSDK.IFileOperation.self) { pThis in
      CHECKED(pThis.pointee.lpVtbl.pointee.ApplyPropertiesToItem(pThis, RawPointer(psiItem)))
    }
  }
```


For `ID3D12CommandList::GetType`, I think that this is the proper implementation:

```swift
public class ID3D12CommandList: ID3D12DeviceChild {
   override public class var IID: IID { IID_ID3D12CommandList }

   public func GetType() throws -> D3D12_COMMAND_LIST_TYPE {
    return try perform(as: WinSDK.ID3D12CommandList.self) { pThis in
      return pThis.pointee.lpVtbl.pointee.GetType(pThis)
    }
   }
 }
```

MSDN documents it [here](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12commandlist-gettype) as

```c++
D3D12_COMMAND_LIST_TYPE GetType();
```

**Comment by STREGAsGate** [comment]
Hmmm, I guess I'm getting overly excited and going out of scope.
For the Direct3D12 package I'm going full modern swift and implementing the original API as is (but swift-like) while deprecating those so the compiler can suggest the new names. I think that'll be the best user experience and I'm all about the UX.

I'd like to use SwiftCOM as the back end for the package. But I don't want new users to see a pUnk variable on their Queue object. So I was hoping all these changes would allow us to make that variable internal or even private.

Could also move the `perform()` func outside IUnknown and clean up the other stuff that should be internal, I don't have it in front of me...

My thinking is, no matter how hard we try the auto generated interface will be different so everyone who wants to move over to that when it's available will need to refactor anyway. Most will probably just keep these deprecated packages So why not make it as awesome as possible now? If that's too out of scope for what you had planned the package that's cool. I tend to think big.

**Comment by STREGAsGate** [comment]
I've only done enums so far, but [this](https://github.com/STREGAsGate/Direct3D12/blob/master/Sources/Direct3D12/d3d12_h/Enumerations/D3D12_BLEND.swift) is an example of how I'm doing d3d12.

The real type name won't contain the ID3D12 prefix. So it can't share a package with anything or there could be conflicts.
The original ID3D12Type names are implemented as deprecated type aliases. So if someone uses one the correct one will get suggested.

I will be moving them around and making the type aliases global as I do object and structs so that layout isn't final.

**Comment by compnerd** [comment]
> For the Direct3D12 package I'm going full modern swift and implementing the original API as is (but swift-like) while deprecating those so the compiler can suggest the new names. I think that'll be the best user experience and I'm all about the UX.

Very cool!  I hope that you will be sharing the work that you do here.

> I'd like to use SwiftCOM as the back end for the package. But I don't want new users to see a pUnk variable on their Queue object.

But that is exactly what I would like to see.  The idea is that Swift/COM is useful because it gives you a reasonable access to the interface, but in a very raw form as it is beyond the scope of this specific project to create the nice APIs.  Layering atop of it, you could have a modern Swift friendly API.  The user shouldn't have to deal with `IUnknown.pUnk`, but can use `IUnknown` types to use `QueryInterface` to cast.  What exactly did you have in mind wrt `pUnk` variables?

> So I was hoping all these changes would allow us to make that variable internal or even private.

Sadly not, the variable should remain `open` or `public` because I want to allow someone to experiment more rapidly by implementing the bindings outside of the package if they so desire.  I am of course welcoming of attempts to add additional bindings here for COM interfaces that are part of the OS.

> My thinking is, no matter how hard we try the auto generated interface will be different so everyone who wants to move over to that when it's available will need to refactor anyway.

The hope is that we could sink the behavior of this library into the compiler or a binding generator.  The plan here is to simply mechanically transform the IDL definition into a slightly nicer form: C++ -> Swift, convert `out` (or `inout` where the `in` is an output storage ref) into return values, and failed calls into `COMError`.

**Comment by STREGAsGate** [comment]
Absolutely sharing it. I appreciate being able to deploy to windows (the biggest PC gamming platform) and possibly Xbox, so this is me giving back. I only need a tiny fraction of d3d12 personally, but I'm planning to do the entire interface. I'll be attaching the same license you're using for SwiftCOM. The package will rarely change so you're free to stick it in the toolchain too since it's technically a core part of Windows that might make sense.

**Comment by compnerd** [comment]
One other option would be to release it under the Apache license (like the Swift project).

**Comment by STREGAsGate** [comment]
After looking at them I think the Apache 2 does make more sense for it. I went with that.

It's going to be a few weeks before I'll be doing the class implementations I think, so there's no big rush to finalize these changes.
Did you see my idea [here](https://gist.github.com/STREGAsGate/0458531542ca3a887fc6e37fcd506778)? Doing it this way shouldn't add any overhead but it does keep us from having a ton of extra API exposed on IUnknown. It'll also make the implementations much tighter and easier to manage.

**Comment by compnerd** [comment]
I will probably split the work into two changes, doing the `checked` as a follow up.

I did have a look at your suggestion.  I'm not sure I understand the benefit of the wrapper type.  The this pointer is already provided to the closure, and the SDK type doesn't seems to be unused.  The cases where you want to cast to the SDK type is already handled by `RawPointer`.

**Pull request merged**
